version: "3"
services:
  server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  client:
    image: yandex/clickhouse-client
    command: ["--host", "server"]
  rabbitmq:
    image: rabbitmq:3.8.1-management
    container_name: graphlog_que
    ports:
      - 5672:5672
      - 15672:15672
