// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package root

import (
	"github.com/google/wire"
	"github.com/graphlog/heimdall/pkg/config"
	"github.com/graphlog/heimdall/pkg/handlers"
	"github.com/graphlog/heimdall/pkg/server"
	"github.com/graphlog/heimdall/pkg/services"
)

// Injectors from app.go:

func InitializeApp() (*server.AppServer, error) {
	configConfig := config.NewConfig()
	db := services.NewDBConnection(configConfig)
	applicationService := services.NewApplicationService(db)
	connection := services.NewAMQPConnection(configConfig)
	messageService := services.NewMessageService(configConfig, connection)
	requestHandler := handlers.NewRouter(applicationService, messageService)
	appServer := server.CreateServer(configConfig, requestHandler)
	return appServer, nil
}

// app.go:

// AppSet -
var AppSet = wire.NewSet(services.ServiceSet, handlers.RouterSet, server.ServerSet)
