// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package root

import (
	"github.com/google/wire"
	"github.com/graphlog/heimdall/pkg/config"
	"github.com/graphlog/heimdall/pkg/handlers"
	"github.com/graphlog/heimdall/pkg/server"
)

// Injectors from app.go:

func InitializeApp() (*server.AppServer, error) {
	configConfig := config.NewConfig()
	requestHandler := handlers.NewRouter()
	appServer := server.CreateServer(configConfig, requestHandler)
	return appServer, nil
}

// app.go:

// AppSet -
var AppSet = wire.NewSet(handlers.RouterSet, server.ServerSet)
